### ISSUE TITLE
LXMasterBus has an empty model, breaking effects on the master bus

### ISSUE THREAD

**Issue by antonjs** [heronarts/LX#49] opened 2022-02-12 02:03 UTC
This might be by design, so feel free to close it if so.

LXMasterBus has its `model` field set right on startup, and the field isn't updated when the model updates, either through loading a new project or adding new fixtures, and so the `model.points` array remains empty. Any effect that works by iterating over `this.model.points` doesn't work on the master bus because it never receives the model points.

Fine to work around by just iterating over `colors[]`, but raising this because it might also break other things.

Can reproduce by putting `AppEffect` from the LXStudio-IDE distribution on the master bus.

Cheers!

**Comment by mcslee** [comment] 2022-02-14 17:23
Yikes! This is not by design, that's an embarrassingly bad bug. As you also noted, I think I had just always been testing this with master effects that were looping directly on the colors array rather than using the model. Ouch.

I broke this recently on a feature update:
https://github.com/heronarts/LX/commit/d8524cec8ea6b40c74933a89c1c0d627b0fba999

This fixes it:
https://github.com/heronarts/LX/commit/2d16829a727998b7c0e89f152f7ef0ceab7e890a

My apologies! Will be included on the next release.

**Comment by antonjs** [comment] 2022-02-15 22:45
Thanks! I'll give this a test too.

Quick question--as I'm finding small things in LX that could be changed or fixed, as well as having questions come up where it feels like there is a 'right way' to implement something in the LX framework that I can't figure out from the docs, is your preference filing issues, or an email, or just letting small stuff slide? I don't want to spam the repo but also happy to help contribute to improving the software. If there are things I can easily patch I'm also happy to share pull requests.

**Comment by mcslee** [comment] 2022-02-16 00:43
Definitely don't worry about filing too much stuff here, if there are little bugs or issues, I would definitely like to hear about them. Don't feel like you should just let it slide! The more fixed issues the better.

If it's more of a "there must be a way to do this, I'm just not sure what it is" thing, emailing me directly with questions is also fine (mcslee@gmail.com). I know that LX is woefully under-documented, so I'm happy to answer questions and will often also whip up little wiki pages in response to questions that come in. So that ends up being helpful for others as well.

Pull requests are def welcome also, if it's something architecturally substantial or complex, I recommend opening an issue and pinging me first to make sure the issue is fully understood (e.g. this one was definitely a bug, but made sense for you to check with me that there wasn't a subtle architectural reason for what looked like odd behavior).

Thanks for diving in!

**Closed as completed** 2022-11-05 21:38 UTC
Labels: bug
